modLoader = "javafml"
loaderVersion = "[44,)"
issueTrackerURL = "https://github.com/ruvaldak/Semitranslucency/issues"
license = "MIT"

[[mods]]
modId = "translucencyfix"
version = "${version}"
displayName = "Translucency Fix"
logoFile="assets/translucencyfix/icon.png"
authors = "ruvaldak"
description = '''
enables translucency for HUD and GUIs in Minecraft
'''
#logoFile = ""

[[dependencies.translucencyfix]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.translucencyfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.translucencyfix]]
modId = "architectury"
mandatory = true
versionRange = "[7.1.78,)"
ordering = "AFTER"
side = "BOTH"