modLoader="javafml"
# Forge for 1.19 is version 41
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/ruvaldak/Semitranslucency/issues"
showAsResourcePack=false

[[mods]]
    modId="semitranslucency"
    version="1.0.0.0"
    displayName="Translucency Fix"
    #updateJSONURL="minecraftforge.net/versions.json"
    #displayURL="minecraftforge.net"
    logoFile="examplemod.png"
    credits="I'd like to thank my mother and father."
    authors="Author"
    description='''
Lets you craft dirt into diamonds. This is a traditional mod that has existed for eons. It is ancient. The holy Notch created it. Jeb rainbowfied it. Dinnerbone made it upside down. Etc.
    '''
    displayTest="MATCH_VERSION"

[[dependencies.semitranslucency]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.semitranslucency]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
