# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Canary

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        java-package: jdk
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Fabric build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TranslucencyFix-Fabric-Quilt
        path: ./fabric/build/libs
    - name: Upload Forge build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: TranslucencyFix-Forge
        path: ./forge/build/libs
