# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Canary

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Fabric build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: TranslucencyFix-Fabric
        path: fabric/build/libs
    - name: Upload Quilt build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: TranslucencyFix-Quilt
        path: quilt/build/libs
    - name: Upload Forge build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: TranslucencyFix-Forge
        path: forge/build/libs
