# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Canary

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        java-package: jdk
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Fabric build artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./fabric/build/libs/translucencyfix*fabric*quilt*.jar
    - name: Upload Forge build artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./forge/build/libs/translucencyfix*forge*.jar
